// Concepts, not finished taglines. Each category maps to reusable
// semantic material the candidate generator recombines at request time.
// No hardcoded taglines live here — only the ingredients.

export interface CategoryKnowledge {
  aliases: string[];
  nouns: string[];
  desires: string[];
  benefits: string[];
  emotions: string[];
  concepts: string[];
  painPoints: string[];
  positioning: string[];
}

export const CATEGORIES: Record<string, CategoryKnowledge> = {
  furniture: {
    aliases: ["furniture", "furnishing", "interior design", "home decor", "decor", "interiors"],
    nouns: ["furniture", "pieces", "seating", "interiors", "spaces"],
    desires: ["comfort", "a beautiful home", "durability", "a modern look", "customization"],
    benefits: ["custom sizing", "strong materials", "local craftsmanship", "lasting comfort"],
    emotions: ["comfort", "pride", "belonging", "calm"],
    concepts: ["comfort", "craftsmanship", "space", "design", "durability", "home", "shape"],
    painPoints: ["compromise", "flimsy pieces", "waiting months", "a mismatched room"],
    positioning: ["Comfort", "Craftsmanship", "Personalization", "Quality", "Style"],
  },
  fashion: {
    aliases: ["fashion", "fashion designer", "clothing", "boutique", "apparel", "outfit"],
    nouns: ["style", "pieces", "wardrobe", "looks"],
    desires: ["to stand out", "confidence", "a signature look", "clothes that fit right"],
    benefits: ["custom fit", "original designs", "quality fabric", "made to order"],
    emotions: ["confidence", "identity", "pride", "individuality"],
    concepts: ["style", "identity", "fit", "confidence", "craftsmanship", "culture"],
    painPoints: ["looking like everyone else", "a bad fit", "fast-fashion fabric"],
    positioning: ["Style", "Personalization", "Craftsmanship", "Confidence", "Quality"],
  },
  phone_accessories: {
    aliases: ["phone accessories", "phone", "phones", "gadgets", "accessories", "screen repair"],
    nouns: ["devices", "accessories", "gadgets"],
    desires: ["a working phone today", "protection", "reliability", "convenience"],
    benefits: ["same-day repair", "genuine parts", "fair pricing", "fast service"],
    emotions: ["relief", "trust", "convenience"],
    concepts: ["repair", "speed", "restoration", "convenience", "reliability", "device", "trust"],
    painPoints: ["a cracked screen", "waiting days", "fake parts"],
    positioning: ["Speed", "Trust", "Reliability", "Convenience", "Value"],
  },
  electronics: {
    aliases: ["electronics", "electronic", "gadget shop", "tech store"],
    nouns: ["electronics", "devices", "gadgets"],
    desires: ["reliability", "value", "the latest tech", "something that lasts"],
    benefits: ["genuine products", "warranty", "fair prices", "honest advice"],
    emotions: ["trust", "confidence", "excitement"],
    concepts: ["reliability", "performance", "value", "innovation", "power", "trust"],
    painPoints: ["fake products", "overpaying", "no warranty"],
    positioning: ["Trust", "Value", "Innovation", "Reliability"],
  },
  supermarket: {
    aliases: ["supermarket", "grocery", "groceries", "mart", "convenience store"],
    nouns: ["essentials", "groceries", "everyday needs"],
    desires: ["freshness", "convenience", "everything in one place", "fair prices"],
    benefits: ["fresh stock", "wide variety", "everyday low prices"],
    emotions: ["ease", "relief", "trust"],
    concepts: ["freshness", "convenience", "variety", "value", "everyday", "home"],
    painPoints: ["running from shop to shop", "stale stock", "high prices"],
    positioning: ["Convenience", "Value", "Freshness", "Reliability"],
  },
  restaurant: {
    aliases: ["restaurant", "eatery", "diner", "food", "catering"],
    nouns: ["meals", "dishes", "food"],
    desires: ["good taste", "a satisfying meal", "comfort", "a good moment with people"],
    benefits: ["fresh ingredients", "made to order", "generous portions"],
    emotions: ["satisfaction", "comfort", "joy", "warmth"],
    concepts: ["taste", "flavour", "freshness", "comfort", "moments", "home"],
    painPoints: ["bland food", "a long wait", "small portions"],
    positioning: ["Comfort", "Quality", "Experience", "Value"],
  },
  bakery: {
    aliases: ["bakery", "baker", "cake", "pastries", "confectionery"],
    nouns: ["bakes", "pastries", "treats"],
    desires: ["something fresh", "a sweet moment", "a memorable cake"],
    benefits: ["baked daily", "made to order", "quality ingredients"],
    emotions: ["joy", "warmth", "celebration"],
    concepts: ["freshness", "sweetness", "celebration", "craft", "home"],
    painPoints: ["stale bread", "a forgettable cake"],
    positioning: ["Freshness", "Craftsmanship", "Experience", "Quality"],
  },
  hair_salon: {
    aliases: ["hair salon", "salon", "hairdresser", "hairstylist"],
    nouns: ["hair", "style", "looks"],
    desires: ["a fresh look", "confidence", "healthy hair"],
    benefits: ["skilled stylists", "quality products", "a relaxing visit"],
    emotions: ["confidence", "renewal", "care"],
    concepts: ["style", "confidence", "care", "renewal", "craft"],
    painPoints: ["a rushed job", "damaged hair"],
    positioning: ["Craftsmanship", "Confidence", "Experience", "Style"],
  },
  barber: {
    aliases: ["barber", "barbershop", "barbing"],
    nouns: ["cuts", "grooming", "style"],
    desires: ["a sharp look", "precision", "confidence"],
    benefits: ["skilled hands", "clean lines", "a fresh fade"],
    emotions: ["confidence", "sharpness", "pride"],
    concepts: ["precision", "sharpness", "confidence", "craft", "style"],
    painPoints: ["an uneven cut", "a rushed job"],
    positioning: ["Craftsmanship", "Confidence", "Style", "Reliability"],
  },
  beauty: {
    aliases: ["beauty", "spa", "skincare", "cosmetics", "makeup"],
    nouns: ["beauty", "skin", "glow"],
    desires: ["confidence", "healthy skin", "a natural glow"],
    benefits: ["quality products", "gentle care", "visible results"],
    emotions: ["confidence", "self-care", "renewal"],
    concepts: ["confidence", "glow", "self-care", "beauty", "care"],
    painPoints: ["harsh products", "no visible results"],
    positioning: ["Confidence", "Quality", "Experience", "Personalization"],
  },
  auto_mechanic: {
    aliases: ["auto mechanic", "mechanic", "car repair", "auto repair", "car wash"],
    nouns: ["your car", "your engine", "your ride"],
    desires: ["a car that runs right", "trust", "no surprises"],
    benefits: ["honest diagnosis", "skilled hands", "fair pricing"],
    emotions: ["trust", "relief", "confidence"],
    concepts: ["reliability", "trust", "the road", "performance", "honesty"],
    painPoints: ["guesswork", "overcharging", "breaking down again"],
    positioning: ["Trust", "Reliability", "Craftsmanship", "Value"],
  },
  car_dealer: {
    aliases: ["car dealer", "car sales", "dealership", "auto sales"],
    nouns: ["vehicles", "your next car"],
    desires: ["a car they can trust", "value", "a smooth process"],
    benefits: ["verified vehicles", "fair pricing", "a smooth purchase"],
    emotions: ["trust", "confidence", "freedom"],
    concepts: ["trust", "the road ahead", "freedom", "value", "reliability"],
    painPoints: ["hidden faults", "a stressful purchase"],
    positioning: ["Trust", "Value", "Reliability", "Experience"],
  },
  real_estate: {
    aliases: ["real estate", "realty", "property", "properties"],
    nouns: ["homes", "properties", "spaces"],
    desires: ["a place to call home", "a sound investment", "security"],
    benefits: ["verified listings", "honest advice", "a smooth process"],
    emotions: ["security", "hope", "trust"],
    concepts: ["home", "investment", "security", "opportunity", "trust"],
    painPoints: ["a bad deal", "an unclear process"],
    positioning: ["Trust", "Value", "Experience", "Local expertise"],
  },
  construction: {
    aliases: ["construction", "builder", "building contractor"],
    nouns: ["your build", "your project"],
    desires: ["a build that lasts", "reliability", "quality work"],
    benefits: ["skilled crews", "quality materials", "work done right"],
    emotions: ["trust", "pride", "confidence"],
    concepts: ["strength", "trust", "durability", "craftsmanship"],
    painPoints: ["shortcuts", "delays", "shoddy work"],
    positioning: ["Craftsmanship", "Trust", "Reliability", "Quality"],
  },
  plumbing: {
    aliases: ["plumbing", "plumber"],
    nouns: ["your pipes", "your home"],
    desires: ["a fast fix", "no more leaks", "peace of mind"],
    benefits: ["prompt response", "lasting repairs", "fair pricing"],
    emotions: ["relief", "peace of mind"],
    concepts: ["reliability", "comfort", "peace of mind", "promptness"],
    painPoints: ["a leak that won't quit", "waiting all day"],
    positioning: ["Reliability", "Speed", "Trust", "Value"],
  },
  electrical: {
    aliases: ["electrical", "electrician", "generator", "solar", "solar company"],
    nouns: ["your power", "your home"],
    desires: ["power that stays on", "safety", "no more outages"],
    benefits: ["safe wiring", "reliable installs", "fast response"],
    emotions: ["safety", "relief", "confidence"],
    concepts: ["power", "safety", "reliability", "independence"],
    painPoints: ["outages", "unsafe wiring", "flickering lights"],
    positioning: ["Reliability", "Trust", "Innovation", "Speed"],
  },
  printing: {
    aliases: ["printing", "printer", "print shop"],
    nouns: ["your print", "your brand"],
    desires: ["sharp results", "a brand that looks right", "fast turnaround"],
    benefits: ["sharp quality", "fast turnaround", "fair pricing"],
    emotions: ["pride", "confidence"],
    concepts: ["clarity", "precision", "impact", "professionalism"],
    painPoints: ["blurry prints", "missed deadlines"],
    positioning: ["Quality", "Speed", "Craftsmanship", "Value"],
  },
  photography: {
    aliases: ["photography", "photographer", "photo studio"],
    nouns: ["your moments", "your story"],
    desires: ["memories worth keeping", "a story well told"],
    benefits: ["a trained eye", "quality editing", "a relaxed shoot"],
    emotions: ["nostalgia", "joy", "pride"],
    concepts: ["memory", "story", "moment", "art", "light"],
    painPoints: ["a photo that doesn't do the moment justice"],
    positioning: ["Craftsmanship", "Experience", "Style", "Personalization"],
  },
  event_planning: {
    aliases: ["event planning", "event", "events", "wedding planner"],
    nouns: ["your event", "your day"],
    desires: ["a day that runs smoothly", "a memorable event"],
    benefits: ["careful planning", "trusted vendors", "a calm day"],
    emotions: ["joy", "relief", "celebration"],
    concepts: ["celebration", "ease", "memory", "detail"],
    painPoints: ["chaos on the day", "vendors falling through"],
    positioning: ["Experience", "Reliability", "Craftsmanship", "Personalization"],
  },
  logistics: {
    aliases: ["logistics", "courier", "delivery", "shipping", "transport"],
    nouns: ["your delivery", "your goods"],
    desires: ["it to arrive on time", "peace of mind", "no lost packages"],
    benefits: ["real-time tracking", "on-time delivery", "careful handling"],
    emotions: ["relief", "trust"],
    concepts: ["speed", "reliability", "movement", "trust"],
    painPoints: ["late deliveries", "a lost package"],
    positioning: ["Speed", "Reliability", "Trust", "Convenience"],
  },
  cleaning: {
    aliases: ["cleaning", "cleaner", "janitorial", "laundry"],
    nouns: ["your space", "your home"],
    desires: ["a spotless space", "more free time", "peace of mind"],
    benefits: ["thorough cleaning", "reliable scheduling", "trusted staff"],
    emotions: ["relief", "calm", "freshness"],
    concepts: ["cleanliness", "freshness", "order", "calm"],
    painPoints: ["a mess you don't have time for"],
    positioning: ["Reliability", "Convenience", "Trust", "Simplicity"],
  },
  tailoring: {
    aliases: ["tailoring", "tailor", "seamstress"],
    nouns: ["your fit", "your outfit"],
    desires: ["clothes that fit right", "sharp finishing", "a design made for them"],
    benefits: ["precise measurements", "quality finishing", "made to order"],
    emotions: ["confidence", "pride"],
    concepts: ["fit", "craftsmanship", "precision", "style"],
    painPoints: ["a fit that's slightly off"],
    positioning: ["Craftsmanship", "Personalization", "Style", "Confidence"],
  },
  jewelry: {
    aliases: ["jewelry", "jewellery", "jewelers", "gold"],
    nouns: ["your pieces", "your jewelry"],
    desires: ["something that lasts", "a piece with meaning"],
    benefits: ["genuine materials", "fine craftsmanship"],
    emotions: ["sentiment", "elegance", "pride"],
    concepts: ["elegance", "sentiment", "craftsmanship", "shine"],
    painPoints: ["a piece that tarnishes fast"],
    positioning: ["Craftsmanship", "Quality", "Style", "Personalization"],
  },
  pharmacy: {
    aliases: ["pharmacy", "chemist", "drugstore"],
    nouns: ["your health", "your family"],
    desires: ["genuine medication", "quick service", "trustworthy advice"],
    benefits: ["genuine stock", "prompt service", "knowledgeable staff"],
    emotions: ["trust", "relief", "care"],
    concepts: ["health", "trust", "care", "wellbeing"],
    painPoints: ["fake medication", "a long wait"],
    positioning: ["Trust", "Reliability", "Speed", "Local expertise"],
  },
  fitness: {
    aliases: ["fitness", "gym", "trainer", "workout"],
    nouns: ["your training", "your goals"],
    desires: ["visible results", "motivation", "a plan that works"],
    benefits: ["personalised plans", "expert coaching", "real accountability"],
    emotions: ["confidence", "energy", "discipline"],
    concepts: ["strength", "energy", "discipline", "results"],
    painPoints: ["a plan that doesn't work", "losing motivation"],
    positioning: ["Results", "Personalization", "Experience", "Reliability"],
  },
  education: {
    aliases: ["education", "school", "tutor", "tutoring", "academy"],
    nouns: ["your learning", "your child's future"],
    desires: ["real understanding", "confidence in class", "results that show"],
    benefits: ["patient teaching", "proven methods", "flexible scheduling"],
    emotions: ["confidence", "growth", "pride"],
    concepts: ["growth", "knowledge", "confidence", "opportunity"],
    painPoints: ["falling behind", "losing confidence"],
    positioning: ["Results", "Personalization", "Trust", "Local expertise"],
  },
  computer_services: {
    aliases: ["computer services", "computer repair", "it services", "tech support", "software", "web design", "marketing agency"],
    nouns: ["your systems", "your business"],
    desires: ["things that just work", "fewer headaches", "a system they trust"],
    benefits: ["fast turnaround", "clear communication", "lasting fixes"],
    emotions: ["relief", "confidence"],
    concepts: ["reliability", "performance", "clarity", "support"],
    painPoints: ["downtime", "a fix that doesn't hold"],
    positioning: ["Reliability", "Speed", "Trust", "Innovation"],
  },
  agriculture: {
    aliases: ["agriculture", "farm", "farming", "agro"],
    nouns: ["your harvest", "your table"],
    desires: ["freshness", "reliable supply", "quality produce"],
    benefits: ["fresh harvest", "consistent supply", "quality soil-to-table care"],
    emotions: ["nourishment", "trust"],
    concepts: ["freshness", "growth", "nourishment", "reliability"],
    painPoints: ["inconsistent supply"],
    positioning: ["Freshness", "Reliability", "Value", "Local expertise"],
  },
  building_materials: {
    aliases: ["building materials", "hardware", "cement", "construction materials"],
    nouns: ["your build", "your site"],
    desires: ["materials that hold up", "no delays", "fair pricing"],
    benefits: ["quality stock", "reliable supply", "fair pricing"],
    emotions: ["trust", "confidence"],
    concepts: ["strength", "durability", "reliability", "value"],
    painPoints: ["substandard materials", "delays"],
    positioning: ["Quality", "Reliability", "Value", "Trust"],
  },
  home_appliances: {
    aliases: ["home appliances", "appliance", "appliances"],
    nouns: ["your home", "your kitchen"],
    desires: ["appliances that last", "convenience", "fair pricing"],
    benefits: ["genuine products", "warranty", "reliable after-sales support"],
    emotions: ["convenience", "trust"],
    concepts: ["convenience", "reliability", "value", "comfort"],
    painPoints: ["a fridge that dies early"],
    positioning: ["Reliability", "Value", "Convenience", "Trust"],
  },
};

// Generic fallback for anything not in the list above — built from the
// category text itself plus product concepts, so unknown categories
// never crash and still get category-relevant language.
export const GENERIC: CategoryKnowledge = {
  aliases: [],
  nouns: ["products", "service"],
  desires: ["quality", "reliability", "fair value"],
  benefits: ["reliable service", "fair pricing", "genuine products"],
  emotions: ["trust", "satisfaction"],
  concepts: ["quality", "trust", "value", "service"],
  painPoints: ["inconsistent service"],
  positioning: ["Trust", "Value", "Reliability", "Quality"],
};
